# Generated by Django 2.0.2 on 2018-03-04 21:09

from django.db import migrations, models
import django_upload_path.upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soubor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soubor', models.FileField(upload_to=django_upload_path.upload_path.auto_cleaned_path_uuid4)),
            ],
        ),
    ]
